# This is a modified copy of astropy's .travis.yml

# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get. (need g++ for iminuit install)
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
            - g++


env:
    global:
        # Set defaults to avoid repeating in most cases.
        - NUMPY_VERSION=1.12
        - ASTROPY_VERSION=1.3
        - SCIPY_VERSION=0.19
        - OPTIONAL_DEPS=true
        - MAIN_CMD='python setup.py'

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.6 SETUP_CMD='egg_info'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try Mac OS X
        - os: osx
          env: PYTHON_VERSION=2.7 SETUP_CMD='test'
        - os: osx
          env: PYTHON_VERSION=3.6 SETUP_CMD='test'

        # Try different python versions
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.6 SETUP_CMD='test --remote-data any'

        # Try astropy 1.0 version and some older dependencies
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10 SCIPY_VERSION=0.17 ASTROPY_VERSION=1.0 SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.10 SCIPY_VERSION=0.17 ASTROPY_VERSION=1.0 SETUP_CMD='test'

        # Try disabling optional dependencies
        - os: linux
          env: PYTHON_VERSION=2.7 OPTIONAL_DEPS=false SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.6 OPTIONAL_DEPS=false SETUP_CMD='test'

        # Do a pycodestyle test
        - os: linux
          env: PYTHON_VERSION=3.6 MAIN_CMD='./checkstyle' SETUP_CMD=''

        # coverage test
        - os: linux
          env: PYTHON_VERSION=3.6 SETUP_CMD='test --coverage'

        # Try a doc build
        - os: linux
          env: PYTHON_VERSION=3.6 SETUP_CMD='install; cd docs && make html'

install:
    - source .continuous-integration/travis/setup_environment_$TRAVIS_OS_NAME.sh

# for matplotlib
services:
    - xvfb

script:
    - eval $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == *"--coverage"* ]]; then
        coveralls --rcfile='sncosmo/tests/coveragerc';
      fi
