# This is a modified copy of astropy's .travis.yml

# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get. (need g++ for iminuit install)
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
            - g++

env:
    global:
        # Set defaults to avoid repeating in most cases.
        - NUMPY_VERSION=1.10
        - ASTROPY_VERSION=1.1
        - SCIPY_VERSION=0.17
        - OPTIONAL_DEPS=true
        - MAIN_CMD='python setup.py'

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.4 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try Mac OS X
        - os: osx
          env: PYTHON_VERSION=2.7 SETUP_CMD='test'

        # Check for sphinx doc build warnings
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='build_sphinx -w'

        # Try all python versions
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.4 SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.5 SETUP_CMD='test'

        # Try astropy dev version
        - os: linux
          env: PYTHON_VERSION=2.7 ASTROPY_VERSION=dev SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.5 ASTROPY_VERSION=dev SETUP_CMD='test'

        # Try disabling optional dependencies
        - os: linux
          env: PYTHON_VERSION=2.7 OPTIONAL_DEPS=false SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.5 OPTIONAL_DEPS=false SETUP_CMD='test'

        # Try older numpy versions & astropy versions
        # (conda only has builds for np18 and later for astropy 1.0) 
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.8 SCIPY_VERSION=0.12 ASTROPY_VERSION=0.4 SETUP_CMD='test'

        # Do a PEP8 test
        - os: linux
          env: PYTHON_VERSION=2.7 MAIN_CMD='pep8 sncosmo --count' SETUP_CMD=''

install:
    - source .continuous-integration/travis/setup_environment_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then
        coveralls --rcfile='sncosmo/tests/coveragerc';
      fi
